### ISSUE TITLE
Type error running "npm run demo"

### ISSUE THREAD

**Issue by glangmead** [leanprover/lean-client-js#1]
I had never used Node.js before. Here are the commands I ran after cloning this repo:

brew install npm
npm install -g typescript
npm install
npm run bootstrap
npm run demo

These commands succeeded except the last one. I got the output below:

```
$ npm run demo

> lean-client-js@1.0.0 demo /Users/gna/dev/lean-client-js
> cd lean-client-js-browser && webpack-dev-server

Project is running at http://localhost:8080/
webpack output is served from /
Content not from webpack is served from /Users/gna/dev/lean-client-js/lean-client-js-browser/dist
ts-loader: Using typescript@2.3.4 and /Users/gna/dev/lean-client-js/lean-client-js-browser/tsconfig.json
ts-loader: Using typescript@2.3.4 and /Users/gna/dev/lean-client-js/lean-client-js-browser/tsconfig.json
Hash: c7ce82fce6f645a7a6f3
Version: webpack 2.6.1
Time: 3397ms
                         Asset       Size  Chunks                    Chunk Names
ab66a32dc599a8f543ff.worker.js     897 kB          [emitted]  [big]  
                demo_bundle.js    1.21 MB       0  [emitted]  [big]  main
            lib/src/index.d.ts   95 bytes          [emitted]         
        lib/src/inprocess.d.ts  917 bytes          [emitted]         
        lib/src/webworker.d.ts  534 bytes          [emitted]         
  lib/src/webworkerscript.d.ts    0 bytes          [emitted]         
   lib/src/webworkertypes.d.ts  394 bytes          [emitted]         
                 lib/demo.d.ts    0 bytes          [emitted]         
                    index.html  188 bytes          [emitted]         
chunk    {0} demo_bundle.js (main) 1.19 MB [entry] [rendered]
   [35] ./demo.ts 1.64 kB {0} [built] [1 error]
   [36] ../~/webpack-dev-server/client?http://localhost:8080 5.78 kB {0} [built]
   [40] ./src/index.ts 300 bytes {0} [built] [1 error]
   [41] ./src/inprocess.ts 7.4 kB {0} [built] [1 error]
   [42] ./src/webworker.ts 2.58 kB {0} [built] [1 error]
   [47] ../~/events/events.js 8.33 kB {0} [built]
   [48] ../~/html-entities/index.js 231 bytes {0} [built]
   [53] ../~/punycode/punycode.js 14.7 kB {0} [built]
   [56] ../~/querystring-es3/index.js 127 bytes {0} [built]
   [85] ../~/strip-ansi/index.js 161 bytes {0} [built]
   [88] ../~/url/url.js 23.3 kB {0} [built]
   [90] ../~/webpack-dev-server/client/overlay.js 3.73 kB {0} [built]
   [91] ../~/webpack-dev-server/client/socket.js 897 bytes {0} [built]
   [93] ../~/webpack/hot/emitter.js 77 bytes {0} [built]
   [95] multi ../~/webpack-dev-server/client?http://localhost:8080 ./demo.ts 40 bytes {0} [built]
     + 81 hidden modules

ERROR in ./demo.ts
(20,29): error TS2339: Property 'Server' does not exist on type 'typeof "/Users/gna/dev/lean-client-js/lean-client-js-browser/src/index"'.

ERROR in /Users/gna/dev/lean-client-js/lean-client-js-browser/src/webworkertypes.ts
(1,49): error TS2307: Cannot find module 'lean-client-js-core'.

ERROR in ../~/worker-loader!./src/webworkerscript.ts
(1,26): error TS2307: Cannot find module 'lean-client-js-core'.

ERROR in ./src/webworker.ts
(1,60): error TS2307: Cannot find module 'lean-client-js-core'.

ERROR in ./src/inprocess.ts
(2,60): error TS2307: Cannot find module 'lean-client-js-core'.

ERROR in ./src/index.ts
(1,15): error TS2307: Cannot find module 'lean-client-js-core'.

ERROR in ./src/index.ts
Module not found: Error: Can't resolve 'lean-client-js-core' in '/Users/gna/dev/lean-client-js/lean-client-js-browser/src'
 @ ./src/index.ts 9:9-39
 @ ./demo.ts
 @ multi ../~/webpack-dev-server/client?http://localhost:8080 ./demo.ts

ERROR in ./src/inprocess.ts
Module not found: Error: Can't resolve 'lean-client-js-core' in '/Users/gna/dev/lean-client-js/lean-client-js-browser/src'
 @ ./src/inprocess.ts 13:28-58
 @ ./src/index.ts
 @ ./demo.ts
 @ multi ../~/webpack-dev-server/client?http://localhost:8080 ./demo.ts

ERROR in ./src/webworker.ts
Module not found: Error: Can't resolve 'lean-client-js-core' in '/Users/gna/dev/lean-client-js/lean-client-js-browser/src'
 @ ./src/webworker.ts 8:28-58
 @ ./src/index.ts
 @ ./demo.ts
 @ multi ../~/webpack-dev-server/client?http://localhost:8080 ./demo.ts
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 541 kB [entry] [rendered]
        [0] ../~/lodash/lodash.js 540 kB {0} [built]
        [1] ../~/html-webpack-plugin/lib/loader.js!../~/html-webpack-plugin/default_index.ejs 538 bytes {0} [built]
        [2] ../~/webpack/buildin/global.js 509 bytes {0} [built]
        [3] ../~/webpack/buildin/module.js 517 bytes {0} [built]
Child worker:
                             Asset    Size  Chunks                    Chunk Names
    ab66a32dc599a8f543ff.worker.js  897 kB       0  [emitted]  [big]  main
    chunk    {0} ab66a32dc599a8f543ff.worker.js (main) 893 kB [entry] [rendered]
        [0] ../~/webpack/buildin/global.js 509 bytes {0} [built]
        [1] ./src/inprocess.ts 7.4 kB {0} [built]
        [2] ./~/browserfs/dist/browserfs.js 817 kB {0} [built]
        [3] ../~/babel-loader/lib?presets[]=env!../~/ts-loader!./src/webworkerscript.ts 1.07 kB {0} [built]
        [4] ../~/base64-js/index.js 3.47 kB {0} [built]
        [5] ../~/buffer/index.js 48.6 kB {0} [built]
        [6] ../~/buffer/~/isarray/index.js 132 bytes {0} [built]
        [7] ../~/ieee754/index.js 2.05 kB {0} [built]
        [8] ../~/process/browser.js 5.42 kB {0} [built]
        [9] ../~/setimmediate/setImmediate.js 6.47 kB {0} [built]
       [10] ../~/timers-browserify/main.js 1.36 kB {0} [built]
    
    ERROR in ./src/inprocess.ts
    Module not found: Error: Can't resolve 'lean-client-js-core' in '/Users/gna/dev/lean-client-js/lean-client-js-browser/src'
     @ ./src/inprocess.ts 13:28-58
     @ ../~/babel-loader/lib?presets[]=env!../~/ts-loader!./src/webworkerscript.ts
webpack: Failed to compile.
```

**Comment by glangmead** [comment]
I'm on macOS 10.12.5. I have lean installed on my path at /usr/local/bin/lean.

**Comment by glangmead** [comment]
Like I said I don't know what I'm doing with npm, but if i run `npm run compile` (in fact I got some errors until I ran it a second time), and then `npm run demo`, then the server actually runs. However it says "look in the console" and in the console is an error 

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (browserfs.js.map, line 0)
```
as well as
```
[Error] ReferenceError: Can't find variable: WebAssembly (9ac7479cf58b7ed0fc38.worker.js, line 258)
```

**Comment by gebner** [comment]
Sorry, I completely missed this issue.  (I forgot to click "watch" on this repository.)

There were two issues, and they should be fixed now:
 1. You need to call `npm run compile` before starting the demo.  This step was missing from the README.
 2. There was a build error with TypeScript 2.4, which was released yesterday.

**Comment by glangmead** [comment]
Thanks, it builds cleanly now. I still have the Can't find variable: WebAssembly error in the console with "npm run demo", but this particular issue is closed.
